# Generated by Django 3.2.5 on 2021-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoleksiAirfoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('re', models.FloatField()),
                ('alpha', models.FloatField()),
                ('cp_upper', models.TextField()),
                ('cp_lower', models.TextField()),
                ('cl', models.FloatField()),
                ('cd', models.FloatField()),
                ('cm', models.FloatField()),
                ('sdf', models.ImageField(upload_to='airfoil')),
            ],
            options={
                'verbose_name_plural': 'Koleksi Airfoil',
                'ordering': ['nama', 'alpha'],
            },
        ),
        migrations.AddIndex(
            model_name='koleksiairfoil',
            index=models.Index(fields=['nama', 'alpha'], name='flow_koleks_nama_2d3480_idx'),
        ),
    ]
