# Generated by Django 3.2.5 on 2021-09-14 04:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20210909_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksiairfoil',
            name='cp_lower',
        ),
        migrations.RemoveField(
            model_name='koleksiairfoil',
            name='cp_upper',
        ),
        migrations.AddField(
            model_name='koleksiairfoil',
            name='cp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='koleksiairfoil',
            name='x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
