# Generated by Django 3.2.5 on 2021-09-14 04:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20210914_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koleksiairfoil',
            name='cp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='koleksiairfoil',
            name='x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
